# 这是一个 mods.toml 示例文件，包含与加载 Mod 相关的数据。
# 其中有几个必填字段（#mandatory），以及更多可选字段（#optional）。
# 整体格式为标准 TOML 格式，版本 v0.5.0。
# 请注意，此文件中包含几个 TOML 列表。
# 可在此处了解更多 TOML 格式信息：https://github.com/toml-lang/toml
# 要加载的 Mod 加载器类型名称 - 对于常规 FML @Mod Mod，应为 javafml
modLoader = "javafml" #mandatory
# 用于匹配上述 Mod 加载器的版本范围 - 对于常规 FML @Mod，这是 FML 版本。目前为 47。
loaderVersion = "${loader_version_range}" #mandatory
# 你的 Mod 的许可证。这是必填元数据，便于理解你的再分发属性。
# 可在 https://choosealicense.com/ 查看可选许可证。保留所有权利是默认版权立场，因此这里也以其为默认值。
license = "${mod_license}"
# 当此 Mod 出现问题时，引导用户前往的 URL
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# Mod 列表 - 此处允许多少个 Mod 由各个 Mod 加载器决定
[[mods]] #mandatory
# Mod 的 modid
modId = "${mod_id}" #mandatory
# Mod 的版本号
version = "${mod_version}" #mandatory
# Mod 的显示名称
displayName = "${mod_name}" #mandatory
# 用于查询此 Mod 更新的 URL。请参阅 JSON 更新规范：https://docs.neoforge.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# 此 Mod 的“主页”URL，会显示在 Mod UI 中
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# 包含显示用徽标的文件名（位于 Mod JAR 根目录中）
#logoFile="enigmatic_legacy.png" #optional
# 显示在 Mod UI 中的文本字段
#credits="" #optional
# 显示在 Mod UI 中的文本字段
authors = "${mod_authors}" #optional

# Mod 的描述文本（多行！）（#mandatory）
description = '''${mod_description}'''

# [[mixins]] 块允许你向 FML 声明 mixin 配置，以便加载它。
[[mixins]]
config = "${mod_id}.mixins.json"

# [[accessTransformers]] 块允许你声明 AT 文件的位置。
# 如果省略此块，将回退尝试从 META-INF/accesstransformer.cfg 加载 AT
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# coremods 配置文件路径不可配置，始终从 META-INF/coremods.json 加载

# 一个依赖项 - 使用 . 表示针对特定 modid 的依赖项。依赖项是可选的。
[[dependencies."${mod_id}"]] #optional
# 依赖项的 modid
modId = "neoforge" #mandatory
# 依赖项的类型。可以是 "required"、"optional"、"incompatible" 或 "discouraged" 之一（大小写不敏感）。
# 'required' 要求该 Mod 存在，'optional' 则不要求
# 如果该 Mod 存在，'incompatible' 会阻止游戏加载，'discouraged' 会显示警告
type = "required" #mandatory
# 可选字段，用于描述为什么需要该依赖项，或为什么它不兼容
# reason="..."
# 依赖项的版本范围
versionRange = "${neo_version_range}" #mandatory
# 与依赖项之间的加载顺序关系。
# BEFORE - 此 Mod 在依赖项之前加载
# AFTER - 此 Mod 在依赖项之后加载
ordering = "NONE"
# 此依赖项适用的端 - BOTH、CLIENT 或 SERVER
side = "BOTH"
# 这是另一个依赖项
[[dependencies."${mod_id}"]]
modId = "curios"
type = "required"
# Curios 9.x 对应 Minecraft 1.21.1 的所有版本
versionRange = "${curios_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "patchouli"
type = "required"
# Patchouli 1.21.1 NeoForge 稳定发布线
versionRange = "${patchouli_version_range}"
ordering = "NONE"
side = "BOTH"

# 这是另一个依赖项
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
# 此版本范围声明最低为当前 Minecraft 版本，最高到但不包括下一个主要版本
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# Features 是游戏环境的特定属性，你可能需要声明你的 Mod 依赖这些属性。此示例声明
# 你的 Mod 需要 GL 版本 3.2 或更高。未来会添加其他 feature。它们会感知端，因此声明此项
# 例如不会阻止你的 Mod 在服务器上加载。
#[features."${mod_id}"]
#openGLVersion="[3.2,)"
